### PR TITLE
I think the issue might be that the files for each person need to be saved as a .md file. 

### PR DESCRIPTION
**Pull request by luran1**
One of the only major changes that I could find between other peoples files and the ones that were previously working on the site is that the files that they were saved as was a .md file. I've gone ahead and changed all the files so that they look like a .md file and I've also commented a javascript that I wanted to use as a people sorter in case that was also causing issues. 

I don't think that I can see the website change on my end without it being committed to the master branch so I can't directly tell if this will fix the problem but when I was looking at what the file type changed it seemed to fix some of the files text rendering problems.

### CODE REVIEW

**Comment by GalaxyDream** [comment]
Greetings Luran,

I think you might be able to see the change on your local machine before "commit". As stated on "https://help.github.com/en/articles/setting-up-your-github-pages-site-locally-with-jekyll#step-1-create-a-local-repository-for-your-jekyll-site", you can run `bundle exec jekyll serve`, then browse `http://localhost:4000` to see the website locally. I have tried it successfully on my local machine.

Let me know if you encounter problems with above method.

**Comment by luran1** [comment]
Hey Xinsong,

I'm having issues getting ruby to install on my window machine. Because of
this I don't know how to test run the webpage prior to merger.

If we could meet some time to discuss and find a solution for this that
would be great.

Best regards,
Luran Manfio

**Comment by GalaxyDream** [comment]
Sure, I did not use Windows, but I will try to solve your problem. How about Friday 2pm in Modular?

Cheers,

Xinsong

**Comment by luran1** [comment]
Friday at 2 would be great, thank you.

**Comment by GalaxyDream** [comment]
Perfect!

**Pull request merged**
